### PR TITLE
Fix bug on Find command: Invalid cuisine keyword doesn’t show appropriate error message

### LINKED ISSUE #193: Find command: Invalid cuisine keyword doesn’t show appropriate error message
The find command fails to show an appropriate error message when the cuisine keyword is invalid.

### PR DESCRIPTION
**Pull request by sjinho**
close #193

### CODE REVIEW

File: src/main/java/seedu/bitebuddy/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -83,11 +84,15 @@ private List<String> extractTags(ArgumentMultimap argMultimap) {
...
-                .map(String::trim)
-                .filter(s -> !s.isEmpty())
-                .map(Cuisine::new);
+    private Optional<Cuisine> extractCuisine(ArgumentMultimap argMultimap) throws ParseException {
+        try {
+            return argMultimap.getValue(PREFIX_CUISINE)
+                    .map(String::trim)
+                    .filter(s -> !s.isEmpty())
+                    .map(Cuisine::new);
+        } catch (IllegalArgumentException e) {
```
Comment (keitht8y) [inline src/main/java/seedu/bitebuddy/logic/parser/FindCommandParser.java]: Great way to gracefully catch the error thrown by invalid cuisine keywords!
